Pricing page riddl definition (#27)
improving-ottawa/kalix-improving-template pull request #43
Opened 2023-11-17 23:24 UTC by JamesYopp

Pricing page RIDDL definition. Also corrected form syntax in signup and signin riddl definitions

2023-11-20 14:07 UTC, reid-spencer requested changes

2023-11-20 14:07 UTC, reid-spencer commented on design/src/main/riddl/application/pages/pricing.riddl
> +  products: ksoTemplateAppDomain.ksoTemplateApp.ProductDisplayInfo*
You should now (with riddlc 0.27.7) be able to shorten that path identifier. Ir "ProductDisplayInfo" is unique, you don't need anything else. If it is unique within ksoTemplateApp, you only need those last two parts, etc. Apply this rule across your changes since I think it significantly improves readability.  If you have an ambiguity, resolve it by using the smallest necessary path.  If you think it helps readability then feel free to use an appropriate length path (no need to go to the Root or top level domain, the closest ancestor should do)

2023-11-20 14:07 UTC, reid-spencer commented on design/src/main/riddl/application/pages/pricing.riddl
> +}
You should provide some length and value ranges on each of those three fields

2023-11-20 14:07 UTC, reid-spencer commented on design/src/main/riddl/application/pages/pricing.riddl
> +  ProductInformationText: String briefly "High-level description of the product offering"
min/max length bounds should be specified

2023-11-20 14:07 UTC, reid-spencer commented on design/src/main/riddl/application/pages/pricing.riddl
> +  output PricingPageText showsksoTemplateAppDomain.ksoTemplateApp. ProductOfferingText
That shouldn't compile as there's a space before ProductOfferingText.  If it does compile, please file a bug in the reactific/riddl project.  There is also a missing space after "shows".  There is also a missing type keyword after "shows".  It should be like:
```
output PricingPageText shows record ProductOfferingText
```

2023-11-21 19:40 UTC, JamesYopp commented on design/src/main/riddl/application/pages/pricing.riddl
> +  output PricingPageText showsksoTemplateAppDomain.ksoTemplateApp. ProductOfferingText
riddl issue [#486](https://github.com/reactific/riddl/issues/486) was created

2023-11-21 22:11 UTC, closed without merging

2023-11-21 22:11 UTC, JamesYopp commented
All changes were included in a separate PR