Shipping page riddl defintion (#28)
improving-ottawa/kalix-improving-template pull request #44
Opened 2023-11-18 01:23 UTC by JamesYopp

Commit this PR after #27

2023-11-20 14:17 UTC, reid-spencer requested changes

2023-11-20 14:17 UTC, reid-spencer commented on design/src/main/riddl/application/pages/fragments/checkoutStepper.riddl
> +  activeStep: ksoTemplateAppDomain.ksoTemplateApp.ActiveStep briefly "which step is the user on in the checkout process"
Probably don't need that long path? `ActiveStep` should be enough. If not, please file a bug on riddl

2023-11-20 14:17 UTC, reid-spencer commented on design/src/main/riddl/application/pages/fragments/checkoutStepper.riddl
> +  confirm: String briefly "text indicating the user is on the order confirmation step",
The above Strings should likely not have unlimited length or be valid if they are empty. I suggest you create a string type  like: `type StepText = String(2, 32)` and use it on each of those above fields

2023-11-20 14:17 UTC, reid-spencer commented on design/src/main/riddl/application/pages/shippingAddress.riddl
> +//}
I would like to understand more about this.  What's the motivation for this sequence of commands as a function? Eliminate redundancy?  Sequence is used in multiple places?

2023-11-20 14:17 UTC, reid-spencer commented on design/src/main/riddl/application/pages/signin.riddl
>      selector rememberMeOption accepts ksoTemplateAppDomain.ksoTemplateApp.RememberMe
I assume since the path on this file includes "application" that this page is in the context of `ksoTemplateApp`; so, I'm wondering if this path identifier will succeed without the `ksoTemplateAppDomain` part?  If those conditions hold and you get an error without the first part, please file a bug on riddl

2023-11-21 20:22 UTC, JamesYopp commented on design/src/main/riddl/application/pages/signin.riddl
>      selector rememberMeOption accepts ksoTemplateAppDomain.ksoTemplateApp.RememberMe
It does not create an error. Marking resolved.

2023-11-21 20:23 UTC, JamesYopp commented on design/src/main/riddl/application/pages/fragments/checkoutStepper.riddl
> +  activeStep: ksoTemplateAppDomain.ksoTemplateApp.ActiveStep briefly "which step is the user on in the checkout process"
It turns out I was not using the CheckoutStepper type so I removed it.

2023-11-21 20:24 UTC, JamesYopp commented on design/src/main/riddl/application/pages/shippingAddress.riddl
> +//}
I will leave a note to discuss this futher with you. I don't believe I have used a Sequence in Riddl.

2023-11-21 20:26 UTC, JamesYopp commented on design/src/main/riddl/application/pages/fragments/checkoutStepper.riddl
> +  confirm: String briefly "text indicating the user is on the order confirmation step",
The CheckoutStepper type was not being used, so I deleted it.

2023-11-21 22:12 UTC, JamesYopp commented
All changes were included in a separate PR

2023-11-21 22:12 UTC, closed without merging