Payment page riddl definition (#29)
improving-ottawa/kalix-improving-template pull request #45
Opened 2023-11-18 03:13 UTC by JamesYopp

Payment page RIDDL definition

2023-11-20 14:51 UTC, reid-spencer requested changes

2023-11-21 20:29 UTC, JamesYopp commented on design/src/main/riddl/application/pages/payment.riddl
> +  cardNumber: String,
I am hoping to demonstrate how we would manage PCI compliance. The easiest way to do this is to delegate the PaymentInfo form to the credit card processor. What we should persist on our end is a credit card token. We will not know the pattern or length of this token as it varies from processor to processor.

2023-11-21 20:37 UTC, JamesYopp commented on design/src/main/riddl/application/pages/payment.riddl
> +type CopyPaymentInfoFromBillingInfo: Boolean
The issue I ran into is I needed a type later when I was defining inputs for the form. I could not say:

`selector savePaymentInfoToProfile accepts Boolean`

This results in the following error:
`[error] Error: application/pages/payment.riddl(34:47):
Path 'Boolean' was not resolved, in selector 'savePaymentInfoToProfile'
and it should refer to a Type:
    selector savePaymentInfoToProfile accepts Boolean
                                              ^`

2023-11-21 20:39 UTC, JamesYopp commented on design/src/main/riddl/ksoapp.md
> +TODO: Demonstrate PII best practices -- encrypt PII for storage
These comments are in a *.md file. Why would they not compile?

2023-11-21 22:10 UTC, closed without merging

2023-11-21 22:10 UTC, JamesYopp commented
All changes were included in a separate PR